---
abstract: 'MogileFS client library'
author:
  - 'Brad Fitzpatrick <brad@danga.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MogileFS-Client
no_index:
  directory:
    - t
    - inc
requires:
  IO::WrapTie: 2.102
  LWP::Simple: 0
  List::Util: 0
  Test::More: 0
  Time::HiRes: 0
  fields: 0
version: 1.17
